field: 5802a951-4ced-4184-8d23-fddc691ce839 # Sub Items
fieldLayouts:
  c3607cdf-4946-4234-a7b7-d52989398639:
    tabs:
      -
        elements:
          -
            fieldUid: bd5d1f55-1bf1-4d06-98e3-90ae4759742b # Item
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0aa7afbd-684c-4a4f-af35-7ae3e7c880b9 # Url Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0aa7afbd-684c-4a4f-af35-7ae3e7c880b9: # Url Link
    columnSuffix: jkcganuj
    contentColumnType: string(255)
    fieldGroup: null
    handle: urlLink
    instructions: ''
    name: 'Url Link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  bd5d1f55-1bf1-4d06-98e3-90ae4759742b: # Item
    columnSuffix: gvqpilzn
    contentColumnType: text
    fieldGroup: null
    handle: item
    instructions: ''
    name: Item
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: subItems
name: 'Sub Items'
sortOrder: 1
