defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  c7e6038f-b704-4204-a928-cf4f748e7bfc: # test
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
