defaultPlacement: end
enableVersioning: true
handle: article
name: Article
propagationMethod: all
siteSettings:
  6185ef26-b00b-401b-85bc-2cb6404515e9: # test
    enabledByDefault: true
    hasUrls: true
    template: article/_entry
    uriFormat: 'article/{slug}'
  c7e6038f-b704-4204-a928-cf4f748e7bfc: # test
    enabledByDefault: true
    hasUrls: true
    template: article/_entry
    uriFormat: 'article/{slug}'
type: channel
