columnSuffix: null
contentColumnType: string
fieldGroup: 14af1bed-5737-4d11-a22b-a7d7771861f8 # test
handle: category
instructions: ''
name: category
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:905c1817-028b-4b5a-ab70-d4ba2c07a6d6' # Test Categories
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
