columnSuffix: null
contentColumnType: string
fieldGroup: 14af1bed-5737-4d11-a22b-a7d7771861f8 # test
handle: featureImage
instructions: image
name: 'feature image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:c9154e28-0623-4da9-b9e1-2afd9bef38c4' # test
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:c9154e28-0623-4da9-b9e1-2afd9bef38c4' # test
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
