columnSuffix: null
contentColumnType: string
fieldGroup: 14af1bed-5737-4d11-a22b-a7d7771861f8 # test
handle: postcontent
instructions: ''
name: 'post content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
