dateModified: 1683668138
email:
  fromEmail: admin@email.com
  fromName: test
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0fd298cd-f87b-4f08-a5d3-6a5deb210bf8: test-fields # test-fields
    2e3a2b15-024d-467a-b435-4cc4a4b4323a: phone # phone
    905c1817-028b-4b5a-ab70-d4ba2c07a6d6: 'Test Categories' # Test Categories
    6450f524-471e-4614-908d-5f33396a8665: Default # Default
    014176d8-962b-4073-a090-8dabe43014f0: Test # Test
    560322c8-79e5-454b-9d78-f9ad0033a465: test # test
    b8d62b09-4a91-4b9b-be77-1fc5d220c67e: Common # Common
    c7e6038f-b704-4204-a928-cf4f748e7bfc: test # test
    c9154e28-0623-4da9-b9e1-2afd9bef38c4: test # test
    dfdfab0f-ee9e-4d2f-9e38-6400e18877e1: 'test fields' # test fields
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: test
  schemaVersion: 3.8.0.1
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
