fieldLayouts:
  3db265de-dd7b-4df8-9447-e405a0fff42a:
    tabs:
      -
        elements:
          -
            fieldUid: 5c246f26-c83b-4b55-bd8c-e90819d0b161 # site description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: somedescription
        sortOrder: 1
handle: siteInformation
name: 'Site Information'
sortOrder: 1
