dateModified: 1698939420
email:
  fromEmail: admin@email.com
  fromName: test
  replyToEmail: null
  template: null
  transportSettings:
    encryptionMethod: none
    host: mailhog_yii
    password: ''
    port: '1025'
    timeout: '10'
    useAuthentication: '0'
    username: ''
  transportType: craft\mail\transportadapters\Smtp
fs:
  general:
    hasUrls: true
    name: General
    settings:
      path: '@webroot/assets/general'
    type: craft\fs\Local
    url: '@web/assets/general'
  test:
    hasUrls: true
    name: test
    settings:
      path: '@webroot/assets/test'
    type: craft\fs\Local
    url: '@web/assets/test'
meta:
  __names__:
    0a57fc38-192b-46ee-8275-8849950a4589: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    0aa7afbd-684c-4a4f-af35-7ae3e7c880b9: 'Url Link' # Url Link
    0c009da0-e89a-4fa8-baf7-40f6d1236bc2: globalinfos # globalinfos
    0cae2c6d-127d-4017-be10-7209d6b264ba: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    0cf21295-f27e-4708-a923-c025c7ef57a1: uid # uid
    0d703cf7-966c-4ac8-9da2-87a4f4cd8647: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    0e48bf59-2942-4151-9aec-db82d4747108: draftNotes # draftNotes
    0f6393bd-0f6e-4510-b32d-f471d16942b8: field_phone_wzvvhqsf # field_phone_wzvvhqsf
    0fd298cd-f87b-4f08-a5d3-6a5deb210bf8: test-fields # test-fields
    1bf81ae8-d5b2-471f-8556-cb3a0d72364a: expiryDate # expiryDate
    1efada25-8c9d-4b21-b070-cb50ca6f5486: dateLastMerged # dateLastMerged
    2c1e5cbd-85b9-4118-80f1-db1cd9dc108f: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    2e3a2b15-024d-467a-b435-4cc4a4b4323a: phone # phone
    2f54e19f-e638-4bd3-937c-e65ce42a69ec: siteId # siteId
    3ab40d41-eb77-44b9-a436-357cf71e083c: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    3b8da78a-236d-4ff2-9691-e9b1e1e1f5d1: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    3ba74a80-3754-4cc2-ae42-5b65884e9e80: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    3be15125-9f07-4280-a6cb-71b9d7533115: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    3c281fad-4476-4954-ba04-eabb0239841f: AboutImage # AboutImage
    3d9ed3dd-e5fc-4dd4-ac65-37e056f04552: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    3d6561ef-9337-4649-9ab3-85fb53d22ca6: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    3e973801-3e37-43a6-b3bb-9359ef27b534: slug # slug
    3ee67eb4-0dc2-418e-a6ec-0e76ff7952c3: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    4b0cffce-d0d3-4c78-b452-782842693eac: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    4ba89ab4-7d06-4166-af83-e29943844182: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    4d4bc2e6-acdd-4ddf-aa84-b7d5aecf099f: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    04d7816c-4518-47b0-b29f-8573bde045ec: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    4ff332ed-51bc-4bec-92fa-d0ce107a1249: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    5a47aea3-200e-4896-a7df-1d941a84541e: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    5c2de38b-c6b6-46c9-899a-6705edec93c4: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    5c9f823f-2baf-4b96-a53d-291711dcd81f: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    5c246f26-c83b-4b55-bd8c-e90819d0b161: 'site description' # site description
    05cd835b-05c1-4cf5-a8cc-3b996c30bc8c: 'feature image' # feature image
    6b317740-4596-4612-a793-ab0ce8cec61c: General # General
    6d256acb-cade-472d-a430-ea13216a8edd: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    6dc7d993-4854-48bc-9bd7-a56e158258c9: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    7b35259b-7a8d-453f-bdc7-4b9037086ddb: About # About
    7c444a57-3530-46fd-a65c-faeb7caa60a1: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    7cc9c6ab-bb42-4bc1-8ce3-128638f3c428: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    7d7e73ba-1668-4e58-bb94-09ac146197ce: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    7d8d6c50-2d48-4b83-801b-29a715b442ce: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    07eef09c-408a-4b6d-8d90-d47e65f2857b: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    7ef22ee0-7e83-4217-9555-de81f0cb06da: Menu # Menu
    8a9841f0-716c-4fcd-b107-e43f66eb14ec: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    8ca25f13-e246-4e08-a468-0b05de7b22c7: summary # summary
    9c576b2f-b619-4785-805c-acd6880135fa: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    9d94e6d9-e648-478a-b8c8-23fe245c1ec7: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    9d124598-8ad5-4b83-bd59-5f88d5f444c4: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    9ddcf4e1-51d5-487d-bec0-7fbbbf7b0c13: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    9e10de0d-07a7-44e6-97c0-c94f544951d4: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    9f07b8c0-ff5e-42ad-bf1f-72a8499e8a00: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    11bd546d-31af-46d9-a65c-14a3d7ed71b0: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    13bbb111-ab98-4bc0-9b36-0389269b9882: field_siteDescription_czjfwlkl # field_siteDescription_czjfwlkl
    14a7ce7d-454a-451e-8655-36fd32c38ddf: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    14af1bed-5737-4d11-a22b-a7d7771861f8: test # test
    14d2d885-92bb-4a8c-ae0a-70641e116b0b: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    015d79bd-fbf6-4e7b-98df-f77aa2e0e265: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    21fa7b4e-9dec-4985-bce3-e072c7eb0b50: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    25c5b39f-b270-425a-9674-5abe38330032: authorId # authorId
    25d93efb-ce8f-47c1-9005-d6a19941667d: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    27a2fa8d-233b-4d1b-af70-509fdcec89af: ﻿id # ﻿id
    29e7eb71-ec15-4687-bbaa-3801ab7c6c5c: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    030ca594-bb73-4e2b-9df0-d218ae0218e1: image # image
    34efebcc-a48e-4a14-bf4f-73802b713f49: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    38ed5fc1-e6cf-4b37-813d-1ba80f55a84b: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    42ba6375-d0e2-4f67-bd52-063d23df3209: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    44a481fa-a706-4265-a39c-9fe5330b24de: About # About
    48a1ca8b-8073-4a1f-b1a7-a03f69961e6f: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    49cdbf1a-5bd8-4b58-945f-b846c29b4a85: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    54e3e665-3f79-46ca-a001-338378d08380: canonicalId # canonicalId
    61d21e72-d2ec-4ed9-88e8-fba75cdcdedd: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    61fd8bc2-1b36-4364-8c03-2babb91d25e3: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    66f0ef9d-a8c5-491e-9d34-e2521377f1a7: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    70d36df7-0a7d-4e84-9932-c307ab87f1d8: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    73ca3e5d-4758-41ca-80c6-6c7302a359ed: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    73e36f7c-ca01-44e9-bbde-ade5f38b9684: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    74a71cf2-5389-4bcf-a7dc-73d67c70f88c: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    85fea831-5aa0-446c-8813-94be523ac222: entriesGus # entriesGus
    90a0a67f-b8a7-40a2-b564-075d862dfe09: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    93d6a828-1327-4a9d-8c76-c26a29cf38fe: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    93fd4994-d853-417f-8e95-940b72a75475: text # text
    95ecc0e2-7689-40da-ab6e-7f703d815917: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    99e490a6-171a-45c8-a71b-1ad4a473d6e9: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    351aae79-e257-4f08-9610-2119c02a072b: draftCreatorId # draftCreatorId
    364ee268-a062-4b2d-b580-d406adbd6337: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    493b8e03-3674-4d6d-8da5-26140b82250f: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    559aefe1-977d-4e92-b7be-e50bf54d2d4c: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    581c9c94-6b3b-47ea-8f3d-0a216c118b23: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    593f8556-823d-4978-8884-094278f70917: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    611f5e5b-de2f-432b-8b6e-1c20f1142086: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    649a724e-d367-4a5e-8bcc-540fe50605d4: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    738a3f72-b511-4d78-a843-8a02382e6c72: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    804d8ab8-4d4f-44ff-b167-0d8638fd66a3: Menu # Menu
    905c1817-028b-4b5a-ab70-d4ba2c07a6d6: 'Test Categories' # Test Categories
    920b54da-fc59-4fdf-9d06-1a1e6a5c1b55: isProvisionalDraft # isProvisionalDraft
    958c4564-74ab-4d0b-be39-17aee25aee17: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    998e7da2-5505-4f8a-bef8-7ab276025642: 'Site Information' # Site Information
    998f8599-4d2e-42e2-90aa-ad320bf8f267: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    1504c7a8-2817-40c8-878f-0c500b106668: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    2643e170-c342-4487-a04e-d7a14edb5a3d: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    3572bce0-c975-493a-9e63-26f6214d66e8: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    3808d8c7-8a64-4280-b67c-0704d81018e3: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    4659b9ae-2afc-4ee5-8f36-e8d22055d9df: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    4820dd1e-bcf8-486a-9d82-21724e0f946b: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    5802a951-4ced-4184-8d23-fddc691ce839: 'Sub Items' # Sub Items
    6450f524-471e-4614-908d-5f33396a8665: GusSec # GusSec
    7029a0b8-ffae-47e6-8b1e-a0e54bc3690d: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    7335cc8c-a137-457d-b534-3aad67569d1c: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    7919f2be-4fb8-4f09-b1f0-6b327218d993: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    9751eae5-1aa5-4268-b78b-bf352343fe15: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    9886b092-c4ea-4ee6-9bb3-cfeb85d0ee47: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    12090ca0-a41e-46e9-a81d-693401ea5890: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    014176d8-962b-4073-a090-8dabe43014f0: GusSection # GusSection
    31663be0-9a4a-4ec7-afe2-009607710c6a: title # title
    37376ee4-e7f6-44f1-aea6-c26dece3085c: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    44453c90-972f-49b9-9f8f-f4b0ed9fd743: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    51126b6f-3fe3-4566-8a77-1c7f1df8f94c: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    59476b32-7354-4f3e-a81b-1254a1e27f49: field_urlLink_egessgbn # field_urlLink_egessgbn
    89040b11-0235-4f4a-a0df-e9ab2409b2fe: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    108074e8-3f9b-4373-9e4c-bcec56af7251: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    124334f3-a875-4f67-9535-17f15e18b88f: draftId # draftId
    223344b3-d430-45c7-94fa-18ea44496187: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    275928c9-b8cc-4382-85df-0376f7e707b3: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    560322c8-79e5-454b-9d78-f9ad0033a465: test # test
    616267d7-70e0-4f72-9031-0d9d12b93851: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    810366eb-d639-4703-a21a-0d4b95313824: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    2928350b-3ce7-4d19-a54b-d0d48cbdae6c: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    06575192-2e90-4fd4-838b-d7ee6d21a397: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    16500952-c8d0-47e4-81f5-0b38088b015c: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    36728867-4e65-4296-ac14-f3797ae90452: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    43420862-e9e4-42cc-a50a-a909cf5e5ea8: fieldLayoutId # fieldLayoutId
    58864396-b891-476d-8aba-139d6eac58fd: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    75135188-10d8-423b-b49a-cc0f6b4dacf9: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    96749248-6794-495d-ace0-56a8f7263166: field_summary_adxqqwux # field_summary_adxqqwux
    a623f8e7-70ac-4394-9930-22ac5e138dbc: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    a56997d8-760a-402e-983f-36739e6eedb8: siteSettingsId # siteSettingsId
    aa9e3145-1f1c-41e1-abb3-c6fad1c8187c: postDate # postDate
    aacd4455-fae1-48ce-972d-2feec6bb7b0b: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    ab0930cb-9959-432c-bb09-67efb5990537: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    acae6709-9e07-4d61-b24e-3ae932dedd8a: 'post content' # post content
    ad4264b8-8e15-4077-afe1-235983799867: enabledForSite # enabledForSite
    af361dfb-2d7c-4d05-845d-3a5c5c7b2889: urlLink # urlLink
    af3891f7-7666-42f3-b79a-20b612c713b3: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    b0d5454a-037d-43be-b9b6-3a401e2f181d: SinglesFields # SinglesFields
    b2e07d45-21c4-4859-a782-2c348e837de2: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    b5a24ab3-dbdc-4cdf-b9a8-d1a16fa7d893: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    b7e42d07-edfa-4470-b50d-4855b147a0ce: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    b8d62b09-4a91-4b9b-be77-1fc5d220c67e: Common # Common
    b8f370aa-efe5-4585-be3c-2571abb628f0: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    b37b3a74-ea11-4ab2-aa91-239096416276: ﻿id # ﻿id
    b503c5a6-b343-416c-b33b-51db9a34dcff: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    b505db89-16b7-4247-a847-9919394e2455: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    b844fcfb-c56d-4642-8e78-b6948b8730f3: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    b8556bdc-084a-4b24-bce2-af0c9f31cd56: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    b60461c4-8b42-42ff-82fd-7ca978f0d27e: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    bc074d1d-a18c-4889-95ec-2a07e1f89fc5: category # category
    bd5d1f55-1bf1-4d06-98e3-90ae4759742b: Item # Item
    bf06e4aa-b9cf-4368-aaac-a2a2bd0b560a: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    c0a31c37-a02d-403a-b1b3-43801090ef06: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    c0b4073f-cdee-4666-a9d8-aaf5508a4c32: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    c0866cd1-faa6-429e-8bca-740fd0491257: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    c7bde790-a738-4dbd-a500-62437160d5b4: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    c7e6038f-b704-4204-a928-cf4f748e7bfc: test # test
    c8bcd2bf-7083-401a-a252-e40c0b946d99: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    c72bdc50-c9e0-46e4-9956-6359ea4b95aa: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    c9154e28-0623-4da9-b9e1-2afd9bef38c4: test # test
    c25787c8-2b93-4ee1-a6fd-f056793ef4c1: enabled # enabled
    c3373708-47f5-4faf-9a55-9dc8bb0e960f: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    c8937161-de84-4611-917c-d352a8944f39: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    cd06007f-20e0-42b5-9f2d-31dffabb91dd: 'Sub Items' # Sub Items
    cd273430-423e-44d1-b630-5671a8a4ea37: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    ce2e2b7d-d1d2-4e90-a3e8-064079f57c83: Default # Default
    d1f2bdfe-ebb6-4063-a24b-7125a7d4d23d: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    d2c78f49-3c09-4282-bb67-e0e80163b214: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    d5d7781b-25f2-4526-8c16-d34fbde395c3: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    d8fede04-ca23-4f54-9866-2d47d21de324: draftName # draftName
    d85e8184-b921-4d5e-8f2f-d42cc12fc175: Menu # Menu
    d422a551-98b6-4d6c-9279-387081b59de3: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    dacf325d-b1c9-456b-993a-97fffa5c5168: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    dbaacb5f-7289-4584-bbe9-0949f0832289: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    dc32641f-bfec-45a9-97c0-ffb1c9d1aeb0: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    dd7d2b1f-d9f1-404b-a158-60d5891b16aa: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    dec44c7d-db83-4dd9-8322-edc8b1cdca9f: uri # uri
    dfce0541-5e40-47e2-88aa-79e6c2e377fd: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    dfdfab0f-ee9e-4d2f-9e38-6400e18877e1: 'test fields' # test fields
    e3f588e9-3045-46d3-9b8e-0cce7e3a7982: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    e9cc6475-b10d-4e17-a4a5-984637808a73: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    e64ea474-ba5c-434c-8545-50ba1d9d58ef: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    e67f0896-55dd-430f-bcf3-8e4bce63d736: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    e404efe6-bc8d-47ca-925d-9d57782d1dce: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    e422d8dc-e794-4cba-8729-34348f5ffa65: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    e459dbd6-0891-4bb3-aacf-9275060edf97: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    ea60daac-3300-4827-a924-2a8489df5270: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    eb74d7fa-b245-427b-af52-f68ef22a9bc8: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    eb85658f-9730-4b5b-8ebb-d8e5736a849d: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    ed063a7c-737d-4599-b86e-82e458578109: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    ed43a8db-66a3-47f3-bfd7-e8b952966759: text # text
    eeaa69f3-fbe9-4c58-9b82-a0d7f4a428fc: typeId # typeId
    efc031cf-e0da-45ca-a209-e25a4271933b: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    f046ce96-3188-40ee-9e6e-1da8f6fcdf82: sectionId # sectionId
    f3bf2d60-f162-431c-bd02-a6f318bf4cca: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    f24c54c7-b2b1-48f7-8af6-d1f13246ed94: contentId # contentId
    f28e5413-644b-4fcd-a293-60a3ca8fa59a: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    f94ccd8b-6137-4a03-b835-932f84667802: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    f432d599-5f69-459b-86dd-bb0a61775e27: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    f740ad66-ec60-4c34-898f-02cfc0e48dde: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    f72740fd-74f1-465b-86a0-fbcb9978f9a8: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    f239622c-0eba-489b-a4f3-6ac171c17322: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    f467654d-0b5a-4f29-9199-6837d03e513f: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    fab38bce-2751-48c0-bc13-0e3006b3a63d: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    fb7b2687-e8af-4945-bc39-f9bfc011886d: image # image
    fb84c479-f849-49aa-9fbe-fe58b625ca26: dateCreated # dateCreated
    fb562b89-75be-401b-9a47-1d558dcf8ae2: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
    fcc2caae-5712-48c8-9a8c-058f71ad3be8: dateUpdated # dateUpdated
    ff1b329e-4cee-4bdb-8149-e99c5e658e71: asdfsadfadsfadsfasd # asdfsadfadsfadsfasd
plugins:
  _exporter:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: test
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
