defaultPlacement: end
enableVersioning: true
handle: cursos
name: Cursos
propagationMethod: all
siteSettings:
  6d8f941c-e69a-48f2-9ac1-179862ecf36e:
    enabledByDefault: true
    hasUrls: true
    template: cursos/_entry
    uriFormat: 'cursos/{slug}'
structure:
  maxLevels: null
  uid: 7bd103ad-f23b-4ea0-8e0e-1984e55a770e
type: structure
